on:
  issues:
    types: [opened]
jobs:
  assign:
    if: contains(github.event.issue.labels.*.name, 'md')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: pozil/auto-assign-issue@v1
        with:
          assignees: ${{ github.actor }}
